#fs1-deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: fs1
spec:
  # 3 Pods should exist at all times.
  selector:
    matchLabels:
      app: fs1
  replicas: 2
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: fs1
    spec:
      containers:
      - name: fs1
        # Run this image
        image: willemveerman/fruitserver:fs1l
        ports:
          - containerPort: 8081
        env:
        - name: FRUITPORT
          value: "8081"
        - name: TARGET_FRUITPORT
          value: "8082"
        - name: TARGET_FRUITSERVER
          value: "fs2"
      imagePullSecrets:
      - name: regcred
