#fs2-deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: fs2
spec:
  # 3 Pods should exist at all times.
  selector:
    matchLabels:
      app: fs2
  replicas: 2
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: fs2
    spec:
      containers:
      - name: fs2
        # Run this image
        image: willemveerman/fruitserver:fs2l
        ports:
          - containerPort: 8082
        env:
        - name: FRUITPORT
          value: "8082"
        - name: TARGET_FRUITPORT
          value: "8081"
        - name: TARGET_FRUITSERVER
          value: "fs1"
      imagePullSecrets:
      - name: regcred